### ISSUE TITLE
Getting a some sort of way to set time

### ISSUE THREAD

**Issue by keanedawg** [mghoffmann/Protaskinate#4]
I am currently working on Protaskinate. 

Since we aren't on Java 8, I can't use a lot of the Java time classes. So we could either 

A.) Change our target OS to one that supports Java 8
B.) Create our own versions of the time classes.

This would be helpful for me because I want to test my algorithm on the actual data types which we'll be using. Currently, I'm am working with Doubles.

**Comment by mghoffmann** [comment]
I think you should just use the Java 8 classes. After we have a polished algorithm, we can make our own mimics of the built-in classes that do only what the algorithm needs them to do to be viable replacements.

If that means upping our target OS, I think that's fine. We can always lower it after we make our own implementations.
